{% set name = "xcube-stac" %}
{% set version = "1.0.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xcube-dev/xcube-stac/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b41e3eb2fe547b24c1ea7ca6e087599eac8bd6c230b18e61c1b60a05cddaaad4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - boto3 ==1.37.3
    - cftime
    - dask
    - h5netcdf
    - libgdal-jp2openjpeg
    - numpy
    - pandas
    - pyproj
    - pystac
    - pystac-client
    - rasterio
    - requests
    - rioxarray
    - xarray
    - xmltodict
    - xcube >=1.11.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - xcube_stac

about:
  summary: xcube-stac provides a data store for accessing data from STAC (SpatioTemporal Asset Catalogs).
  home: https://github.com/xcube-dev/xcube-stac
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: xcube-stac is a Python package
  dev_url: https://github.com/xcube-dev/xcube-stac

extra:
  recipe-maintainers:
    - b-yogesh
    - clarasb
    - forman
    - konstntokas
    - TejasMorbagal
    - thomasstorm
    - TonioF
